org.gradle.jvmargs=-Xmx2048M

mavenCentralPublishing=true
mavenCentralAutomaticPublishing=true
signAllPublications=true

POM_NAME=mapkt
POM_DESCRIPTION=Multiplatform KSP mapping library for Kotlin
POM_URL=https://github.com/jakala-germany/mapkt
POM_LICENSE_NAME=Apache-2.0
POM_LICENSE_URL=https://www.apache.org/licenses/LICENSE-2.0.txt
POM_DEVELOPER_ID=JAKALA Germany
POM_DEVELOPER_NAME=JAKALA Germany
POM_DEVELOPER_URL=https://github.com/jakala-germany/
POM_SCM_URL=https://github.com/jakala-germany/mapkt
POM_SCM_CONNECTION=scm:git:git://github.com/jakala-germany/mapkt.git
POM_SCM_DEV_CONNECTION=scm:git:ssh://github.com/jakala-germany/mapkt.git